version: "3"

services:
  app-rate-limiter:
    container_name: app-rate-limiter
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    env_file:
        - .env
    volumes:
      - ./.env:/.env

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
